### ISSUE TITLE
Missing Power Switch

### ISSUE THREAD

**Issue by bkrajendra** [bkrajendra/sonpakharu#1]
The board do not have a power on off switch
It needs one switch for the last power input to switch ON-OFF battery or supply power off.
Need just a pad, and the switch will be mounted on the case.

**Comment by gauravbhand85** [comment]
added switch and normal pin header footprint

**Comment by gauravbhand85** [comment]
created custom footprint for the ordered switch. Only needs to verify physically now.

**Comment by bkrajendra** [comment]
added header
