### ISSUE TITLE
Board pin map is incorrect.

### ISSUE THREAD

**Issue by bkrajendra** [bkrajendra/sonpakharu#2]
Map the board pins correctly
http://wiki.fluidnc.com/en/hardware/ESP32-S3_Pin_Reference
refer: https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/gpio.html
https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf#iomuxgpio

**Comment by gauravbhand85** [comment]
this has been figured out now

**Comment by gauravbhand85** [comment]
corrected
